USE EMPLOYEE_SERVICE;
CREATE TABLE DEPARTMENT
(
    ID              integer AUTO_INCREMENT,
    DEPARTMENT_NAME varchar(255) NOT NULL,
    CREATED_AT      varchar(30),
    IS_ACTIVE       TINYINT,
    CONSTRAINT DEPARTMENT_ID PRIMARY KEY (ID),
    UNIQUE (DEPARTMENT_NAME)
);

CREATE TABLE EMPLOYEE
(
    ID            integer AUTO_INCREMENT,
    EMPLOYEE_NAME varchar(255) NOT NULL,
    EMAIL         varchar(30)  NOT NULL,
    PHONE         varchar(20)  NOT NULL,
    CREATED_AT      varchar(30),
    DATE_OF_BIRTH      varchar(30),
    IS_ACTIVE       TINYINT,
    DEPARTMENT_ID integer      NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID),
    UNIQUE (EMAIL)
);


