USE EMPLOYEE_SERVICE;
CREATE TABLE DEPARTMENT
(
    ID              integer      NOT NULL AUTO_INCREMENT,
    DEPARTMENT_NAME varchar(100) NOT NULL,
    CONSTRAINT DEPARTMENT_ID PRIMARY KEY (ID),
    UNIQUE (DEPARTMENT_NAME)
);

CREATE TABLE EMPLOYEE
(
    ID            integer      NOT NULL AUTO_INCREMENT,
    EMPLOYEE_NAME varchar(100) NOT NULL,
    EMAIL         varchar(30)  NOT NULL,
    PHONE         varchar(20)  NOT NULL,
    DEPARTMENT_ID integer      NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID),
    UNIQUE (EMAIL, PHONE)
);


